# Generated by Django 5.1.2 on 2024-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text_summary',
            field=models.TextField(blank=True),
        ),
    ]
