# Generated by Django 5.1.2 on 2024-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_document_point_1_document_point_2_document_point_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='point_1',
        ),
        migrations.RemoveField(
            model_name='document',
            name='point_2',
        ),
        migrations.RemoveField(
            model_name='document',
            name='point_3',
        ),
        migrations.AddField(
            model_name='document',
            name='question_list',
            field=models.JSONField(default=list),
        ),
    ]
