# Generated by Django 5.1.2 on 2024-10-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_remove_document_point_1_remove_document_point_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='question_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='question_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
