# Generated by Django 5.1.2 on 2024-11-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_document_question_progress_document_subquestion_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SENTENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='book_app.document')),
            ],
        ),
    ]
