# Generated by Django 5.1.2 on 2024-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_sentence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
