# Generated by Django 5.1.2 on 2024-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='toc',
            field=models.TextField(blank=True),
        ),
    ]
