# Generated by Django 5.1.2 on 2024-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_document_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='toc',
        ),
        migrations.AddField(
            model_name='document',
            name='structed_toc',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
