# Generated by Django 5.1.2 on 2024-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_document_asked_question_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='question_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
